/**
 * Auto-generated sprite sheet frame data
 * Generated by scripts/generate-spritesheet.js
 */

export const SPRITESHEET_PATH = "/images/spritesheet.png";

export const SPRITESHEET_SIZE = {
  width: 2048,
  height: 2048,
};

export interface SpriteFrame {
  x: number;
  y: number;
  w: number;
  h: number;
}

export const SPRITESHEET_FRAMES: Record<string, SpriteFrame> = {
  player_straight: { x: 2, y: 2, w: 1408, h: 736 },
  palm_tree: { x: 1412, y: 2, w: 215, h: 540 },
  tree1: { x: 1629, y: 2, w: 360, h: 360 },
  dead_tree1: { x: 2, y: 740, w: 135, h: 332 },
  column: { x: 139, y: 740, w: 200, h: 315 },
  tree2: { x: 341, y: 740, w: 282, h: 295 },
  billboard09: { x: 625, y: 740, w: 328, h: 282 },
  billboard08: { x: 955, y: 740, w: 385, h: 265 },
  dead_tree2: { x: 1342, y: 740, w: 150, h: 260 },
  boulder1: { x: 1494, y: 740, w: 168, h: 248 },
  billboard02: { x: 1664, y: 740, w: 215, h: 220 },
  billboard03: { x: 2, y: 1074, w: 230, h: 220 },
  boulder3: { x: 234, y: 1074, w: 320, h: 220 },
  billboard05: { x: 556, y: 1074, w: 298, h: 190 },
  billboard06: { x: 856, y: 1074, w: 298, h: 190 },
  billboard07: { x: 1156, y: 1074, w: 298, h: 190 },
  billboard01: { x: 1456, y: 1074, w: 300, h: 170 },
  billboard04: { x: 1758, y: 1074, w: 268, h: 170 },
  bush1: { x: 2, y: 1296, w: 240, h: 155 },
  bush2: { x: 244, y: 1296, w: 232, h: 152 },
  semi: { x: 478, y: 1296, w: 122, h: 144 },
  boulder2: { x: 602, y: 1296, w: 298, h: 140 },
  stump: { x: 902, y: 1296, w: 195, h: 140 },
  cactus: { x: 1099, y: 1296, w: 235, h: 118 },
  truck: { x: 1336, y: 1296, w: 100, h: 78 },
  car02: { x: 1438, y: 1296, w: 80, h: 59 },
  car04: { x: 1520, y: 1296, w: 80, h: 57 },
  car01: { x: 1602, y: 1296, w: 80, h: 56 },
  car03: { x: 1684, y: 1296, w: 88, h: 55 },
  player_uphill_left: { x: 1774, y: 1296, w: 80, h: 45 },
  player_uphill_right: { x: 1856, y: 1296, w: 80, h: 45 },
  player_uphill_straight: { x: 1938, y: 1296, w: 80, h: 45 },
  player_left: { x: 2, y: 1453, w: 80, h: 41 },
  player_right: { x: 84, y: 1453, w: 80, h: 41 },
  player_straight-old: { x: 166, y: 1453, w: 80, h: 41 }
};
