/**
 * Auto-generated sprite sheet frame data
 * Generated by scripts/generate-spritesheet.js
 */

export const SPRITESHEET_PATH = "/images/spritesheet.png";

export const SPRITESHEET_SIZE = {
  width: 2048,
  height: 2048,
};

export interface SpriteFrame {
  x: number;
  y: number;
  w: number;
  h: number;
}

export const SPRITESHEET_FRAMES: Record<string, SpriteFrame> = {
  palm_tree: { x: 2, y: 2, w: 215, h: 540 },
  tree1: { x: 219, y: 2, w: 360, h: 360 },
  dead_tree1: { x: 581, y: 2, w: 135, h: 332 },
  column: { x: 718, y: 2, w: 200, h: 315 },
  tree2: { x: 920, y: 2, w: 282, h: 295 },
  billboard09: { x: 1204, y: 2, w: 328, h: 282 },
  billboard08: { x: 1534, y: 2, w: 385, h: 265 },
  dead_tree2: { x: 2, y: 544, w: 150, h: 260 },
  boulder1: { x: 154, y: 544, w: 168, h: 248 },
  billboard02: { x: 324, y: 544, w: 215, h: 220 },
  billboard03: { x: 541, y: 544, w: 230, h: 220 },
  boulder3: { x: 773, y: 544, w: 320, h: 220 },
  billboard05: { x: 1095, y: 544, w: 298, h: 190 },
  billboard06: { x: 1395, y: 544, w: 298, h: 190 },
  billboard07: { x: 1695, y: 544, w: 298, h: 190 },
  billboard01: { x: 2, y: 806, w: 300, h: 170 },
  billboard04: { x: 304, y: 806, w: 268, h: 170 },
  bush1: { x: 574, y: 806, w: 240, h: 155 },
  bush2: { x: 816, y: 806, w: 232, h: 152 },
  semi: { x: 1050, y: 806, w: 122, h: 144 },
  boulder2: { x: 1174, y: 806, w: 298, h: 140 },
  stump: { x: 1474, y: 806, w: 195, h: 140 },
  cactus: { x: 1671, y: 806, w: 235, h: 118 },
  truck: { x: 1908, y: 806, w: 100, h: 78 },
  car02: { x: 2, y: 978, w: 80, h: 59 },
  car04: { x: 84, y: 978, w: 80, h: 57 },
  car01: { x: 166, y: 978, w: 80, h: 56 },
  car03: { x: 248, y: 978, w: 88, h: 55 },
  player_left: { x: 338, y: 978, w: 88, h: 46 },
  player_right: { x: 428, y: 978, w: 88, h: 46 },
  player_straight: { x: 518, y: 978, w: 88, h: 46 },
  player_uphill_left: { x: 608, y: 978, w: 80, h: 45 },
  player_uphill_right: { x: 690, y: 978, w: 80, h: 45 },
  player_uphill_straight: { x: 772, y: 978, w: 80, h: 45 }
};
